[build.env]
passthrough = ["RUSTUP_TOOLCHAIN"]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install -y --no-install-recommends curl ca-certificates",
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly --target aarch64-unknown-linux-gnu",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install -y --no-install-recommends curl ca-certificates",
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly --target x86_64-unknown-linux-gnu",
]
